$modelname "/home/khang/map_compiler/model_tools/S2GConverter/test/s1_r012-goldsrc.mdl"
$cd "."
$cdtexture "."
$scale 1.0
$texrendermode "metal_light_01_dark.bmp" fullbright 
$texrendermode "metal_light_01_dark.bmp" flatshade 
$texrendermode "mefl2_02_dark.bmp" fullbright 
$texrendermode "mefl2_02_dark.bmp" flatshade 
$texrendermode "chromatic_glass_01.bmp" masked 
$texrendermode "chromatic_glass_01.bmp" fullbright 
$texrendermode "chromatic_glass_01.bmp" flatshade 
$texrendermode "neon_yellow_pulse.bmp" fullbright 
$texrendermode "neon_yellow_pulse.bmp" flatshade 
$texrendermode "circuit_board_yellow.bmp" additive 
$texrendermode "circuit_board_yellow.bmp" fullbright 
$texrendermode "circuit_board_yellow.bmp" flatshade 
$texrendermode "mefl1_02_dark.bmp" fullbright 
$texrendermode "mefl1_02_dark.bmp" flatshade 
$cbox 0 0 0 0 0 0

$bbox -704.25 -1168.952 -272.259 495.592 1024 272.25

$body "studio0" "s1_r012_ref_decompiled_part_nr_1_submodel_0"
$body "studio1" "s1_r012_ref_decompiled_part_nr_2_submodel_0"
$sequence idle "idle"

