$modelname "t1_surf02_nown100wn.mdl"
$cd "\users\Keita\Documents\VHE\J.A.C.K\bspsrc_1.4.3\surf_lt_omnific_d\models\props\surf_lt\nyro"
$cdtexture "\users\Keita\Documents\VHE\J.A.C.K\bspsrc_1.4.3\surf_lt_omnific_d\models\props\surf_lt\nyro"
$cliptotextures
$scale 1.0
$texrendermode glass_cyber_stripes_grey.bmp masked
$texrendermode CHROME_1.bmp additive

$bbox 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
$cbox 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
$eyeposition 0.000000 0.000000 0.000000
$body "mesh" "t1_surf02_nown"
$sequence "idle" "idle" fps 30

$bodygroup body
{
studio "t1_surf02_nown"
}