[package]
name = "gchimp-web"
version.workspace = true
edition.workspace = true

[dependencies]
bsp = { version = "0.1.0", path = "../bsp" }
console_error_panic_hook = "0.1.7"
gchimp = { path = "../gchimp" }
dem = "0.2.0"
zip = { version = "2.2.2", features = ["deflate"], default-features = false }

wasm-bindgen = "0.2.100"
web-sys = "0.3.72"
smd = { version = "0.1.0", path = "../smd" }

[lib]
crate-type = ["cdylib", "rlib"]