[package]
name = "mdl"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.6.0"
byte_writer = { version = "0.1.0", path = "../byte_writer" }
glam = "0.29.2"
nom = "8.0.0"
thiserror = "2.0.12"
