[package]
name = "spr"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
image = { version = "0.25.6", default-features = false, features = ["png"] }
nom = "8.0.0"
thiserror = "2.0.12"
